name: Chacha Ninggolan Bot

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */5 * * *"

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 300

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: package.json

      - name: Install dependencies
        run: npm install

      - name: Jalankan bot (5 jam)
        run: timeout 18000 node bot.js || true
